# we can't meaningfully test this here in open-source land, since it depends
# on commercial software, but let's at least make sure it builds

sudo: false
jdk: oraclejdk8
language: scala
script: sbt publishLocal

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -rf $HOME/.ivy2/local
